#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Analyze same-layer same-class neurons after Neuron-level RSA classification.

This script is designed for the SymbolicKAN model structure used in
Compute_RSA_neuron(30).py. It reads a trained SymbolicKAN checkpoint and the
neuron classification CSV generated by the RSA script, then analyzes grouped
neurons by layer and class label.

It produces:
  1. class_summary.csv
     - class size, RSA score statistics
     - intra-class parameter consistency
     - mean distance to class centroid
     - pairwise distance / cosine similarity
     - optional data-driven functional similarity

  2. ef_param_stats.csv
     - elementary-function parameter strength per class
     - |c|, |w_m c|, |d|, |w_m d| statistics

  3. input_importance_parameter.csv
     - parameter-based input importance I_{l,k,j}

  4. input_importance_data.csv
     - data-weighted input importance, if test data are available

  5. data_contribution_summary.csv
     - actual elementary-function output contribution and base term contribution
       estimated on sampled test data

  6. inter_class_distance.csv
     - centroid distance between classes within the same layer

  7. npz files under class_mean_params/
     - class-wise mean/variance tensors for C, D, base_weight

  8. figures under figures/
     - class centroid-distance heatmaps
     - top input-importance plots
     - elementary-function contribution plots

Typical usage:

python analyze_symbolic_kan_group_weights.py \
  --model_path /path/to/Last_SymbolicKAN_Para_Silu_1_fold_4L_-524-524-524_15_2.pt \
  --class_csv /path/to/neuron_level_rsa_results_r_ge_0.1.csv \
  --data_root /media/aiofm/F/20250723_k-fold-cross-validation-KAN/1-fold \
  --save_dir /path/to/group_weight_analysis

If you only want parameter-space analysis and do not want to load the dataset:

python analyze_symbolic_kan_group_weights.py \
  --model_path /path/to/model.pt \
  --class_csv /path/to/neuron_level_rsa_results_r_ge_0.1.csv \
  --save_dir /path/to/group_weight_analysis \
  --no_dataset_contribution
"""

import os
import re
import math
import argparse
import warnings
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional, Any

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt

try:
    from scipy.spatial.distance import pdist, squareform, cdist
except Exception as exc:  # pragma: no cover
    raise RuntimeError("This script requires scipy. Please install scipy first.") from exc


# =============================================================================
# Elementary functions and SymbolicKAN definition
# =============================================================================

SUPPORTED_ELEMENTARY_FUNCTIONS = {
    "silu": lambda x: torch.nn.functional.silu(x),
    "relu": lambda x: torch.nn.functional.relu(x),
    "sin": lambda x: torch.sin(x),
    "cos": lambda x: torch.cos(x),
    "exp": lambda x: torch.exp(torch.clamp(x, -10, 10)),
    "log": lambda x: torch.log(torch.abs(x) + 1e-6),
    "tanh": lambda x: torch.tanh(x),
    "sigmoid": lambda x: torch.sigmoid(x),
    "sqrt": lambda x: torch.sqrt(torch.abs(x) + 1e-6),
    "square": lambda x: torch.square(x),
    "abs": lambda x: torch.abs(x),
    "identity": lambda x: x,
}

DEFAULT_ELEMENTARY_FUNCTIONS = ["silu", "relu", "tanh", "sigmoid", "abs", "identity"]

BASE_ACTIVATION_MAP = {
    "silu": torch.nn.SiLU,
    "relu": torch.nn.ReLU,
    "tanh": torch.nn.Tanh,
    "sigmoid": torch.nn.Sigmoid,
    "identity": torch.nn.Identity,
}


class SymbolicKANLinear(torch.nn.Module):
    def __init__(
        self,
        in_features: int,
        out_features: int,
        scale_base: float = 1.0,
        scale_mlp: float = 1.0,
        base_activation=torch.nn.SiLU,
        elementary_functions: Optional[List[str]] = None,
    ):
        super(SymbolicKANLinear, self).__init__()

        self.in_features = in_features
        self.out_features = out_features
        self.scale_base = scale_base
        self.scale_mlp = scale_mlp
        self.base_activation = base_activation()

        if elementary_functions is None:
            self.elementary_functions = DEFAULT_ELEMENTARY_FUNCTIONS
        else:
            self.elementary_functions = elementary_functions

        self.num_ef = len(self.elementary_functions)

        # Corresponds to w^b_{l,i,j} in your formula.
        self.base_weight = torch.nn.Parameter(torch.Tensor(out_features, in_features))

        # Corresponds to c_{m,l,i,j}; one [out_features, in_features] matrix per elementary function.
        self.ef_mlp_linears = nn.ParameterList([
            torch.nn.Parameter(torch.Tensor(out_features, in_features))
            for _ in range(self.num_ef)
        ])

        # Corresponds to d_{l,m,i}; one [out_features] vector per elementary function.
        self.ef_mlp_biases = nn.ParameterList([
            torch.nn.Parameter(torch.Tensor(out_features))
            for _ in range(self.num_ef)
        ])

        # Corresponds to w_{l,m}; shared by neurons inside the same layer.
        self.ef_weights = torch.nn.Parameter(torch.ones(self.num_ef))

        self.reset_parameters()

    def reset_parameters(self):
        torch.nn.init.kaiming_uniform_(self.base_weight, a=math.sqrt(5) * self.scale_base)

        for i in range(self.num_ef):
            torch.nn.init.kaiming_uniform_(self.ef_mlp_linears[i], a=math.sqrt(5))
            fan_in, _ = torch.nn.init._calculate_fan_in_and_fan_out(self.ef_mlp_linears[i])
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            torch.nn.init.uniform_(self.ef_mlp_biases[i], -bound, bound)

        torch.nn.init.constant_(self.ef_weights, 1.0 / self.num_ef)

    def apply_elementary_function(self, x, func_idx: int):
        func_name = self.elementary_functions[func_idx]
        mlp_output = nn.functional.linear(
            x,
            self.ef_mlp_linears[func_idx],
            self.ef_mlp_biases[func_idx],
        )
        ef_output = SUPPORTED_ELEMENTARY_FUNCTIONS[func_name](mlp_output)
        return ef_output * self.ef_weights[func_idx]

    def forward(self, x):
        assert x.size(-1) == self.in_features

        original_shape = x.shape
        x = x.reshape(-1, self.in_features)

        base_output = nn.functional.linear(self.base_activation(x), self.base_weight)

        mlp_outputs = []
        for i in range(self.num_ef):
            mlp_outputs.append(self.apply_elementary_function(x, i))

        mlp_output = torch.stack(mlp_outputs, dim=-1).sum(dim=-1) * self.scale_mlp

        output = base_output + mlp_output
        return output.reshape(*original_shape[:-1], self.out_features)


class SymbolicKAN(torch.nn.Module):
    def __init__(
        self,
        layers_hidden: List[int],
        scale_base: float = 1.0,
        scale_mlp: float = 1.0,
        base_activation=torch.nn.SiLU,
        elementary_functions: Optional[List[str]] = None,
    ):
        super(SymbolicKAN, self).__init__()

        self.layers = torch.nn.ModuleList()

        if elementary_functions is None:
            ef_list = DEFAULT_ELEMENTARY_FUNCTIONS
        else:
            ef_list = elementary_functions

        for in_features, out_features in zip(layers_hidden, layers_hidden[1:]):
            self.layers.append(
                SymbolicKANLinear(
                    in_features=in_features,
                    out_features=out_features,
                    scale_base=scale_base,
                    scale_mlp=scale_mlp,
                    base_activation=base_activation,
                    elementary_functions=ef_list,
                )
            )

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x


# =============================================================================
# Utility functions
# =============================================================================


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def parse_int_list(s: str) -> List[int]:
    return [int(x.strip()) for x in s.split(",") if x.strip()]


def parse_str_list(s: str) -> List[str]:
    return [x.strip() for x in s.split(",") if x.strip()]


def sanitize_name(name: Any) -> str:
    name = str(name)
    name = re.sub(r"[^a-zA-Z0-9_\-\.]+", "_", name)
    return name.strip("_") or "unknown"


def layer_name_to_index(layer_name: Any) -> int:
    """Convert 'Layer1' to 0, 'Layer2' to 1, etc."""
    s = str(layer_name)
    nums = re.findall(r"\d+", s)
    if not nums:
        raise ValueError(f"Cannot parse layer index from layer name: {layer_name}")
    return int(nums[-1]) - 1


def index_to_layer_name(layer_idx: int) -> str:
    return f"Layer{layer_idx + 1}"


def load_checkpoint_state(checkpoint: Any, preferred_key: str = "parameter") -> Dict[str, torch.Tensor]:
    """Load model state dict from different possible checkpoint formats."""
    if isinstance(checkpoint, dict):
        candidate_keys = [preferred_key, "parameter", "state_dict", "model_state_dict", "net", "model"]
        for key in candidate_keys:
            if key in checkpoint and isinstance(checkpoint[key], dict):
                return checkpoint[key]

        # Some checkpoints are already plain state dicts.
        if all(isinstance(k, str) for k in checkpoint.keys()):
            tensor_like = [torch.is_tensor(v) for v in checkpoint.values()]
            if len(tensor_like) > 0 and sum(tensor_like) / len(tensor_like) > 0.5:
                return checkpoint

    raise ValueError(
        "Cannot find a valid state_dict in checkpoint. "
        "Try setting --checkpoint_key to the correct key."
    )


def load_symbolic_kan_model(args, device: str) -> SymbolicKAN:
    layers_hidden = parse_int_list(args.layers_hidden)
    elementary_functions = parse_str_list(args.elementary_functions)

    unknown = [f for f in elementary_functions if f not in SUPPORTED_ELEMENTARY_FUNCTIONS]
    if unknown:
        raise ValueError(f"Unsupported elementary function(s): {unknown}")

    if args.base_activation not in BASE_ACTIVATION_MAP:
        raise ValueError(f"Unsupported base activation: {args.base_activation}")

    net = SymbolicKAN(
        layers_hidden=layers_hidden,
        scale_base=args.scale_base,
        scale_mlp=args.scale_mlp,
        base_activation=BASE_ACTIVATION_MAP[args.base_activation],
        elementary_functions=elementary_functions,
    ).to(device)

    checkpoint = torch.load(args.model_path, map_location=device)
    state_dict = load_checkpoint_state(checkpoint, preferred_key=args.checkpoint_key)

    # Remove possible 'module.' prefix from DataParallel checkpoints.
    cleaned_state_dict = {}
    for k, v in state_dict.items():
        new_k = k.replace("module.", "", 1) if k.startswith("module.") else k
        cleaned_state_dict[new_k] = v

    missing, unexpected = net.load_state_dict(cleaned_state_dict, strict=False)
    if missing:
        print("[Warning] Missing keys when loading checkpoint:", missing)
    if unexpected:
        print("[Warning] Unexpected keys when loading checkpoint:", unexpected)

    net.eval()
    return net


def resolve_class_csv(args) -> str:
    if args.class_csv:
        if not os.path.isfile(args.class_csv):
            raise FileNotFoundError(f"--class_csv does not exist: {args.class_csv}")
        return args.class_csv

    # Try to find the common outputs of Compute_RSA_neuron(30).py.
    candidates = [
        os.path.join(args.rsa_save_dir, f"neuron_level_rsa_results_r_ge_{args.r_threshold}.csv"),
        os.path.join(args.rsa_save_dir, "neuron_level_rsa_results.csv"),
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p

    raise FileNotFoundError(
        "Cannot find classification CSV. Please pass --class_csv explicitly. Tried:\n" +
        "\n".join(candidates)
    )


def load_classification_df(args) -> pd.DataFrame:
    class_csv = resolve_class_csv(args)
    df = pd.read_csv(class_csv)

    required = {"layer", "neuron", args.class_col}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Classification CSV lacks required column(s): {missing}")

    df = df.copy()
    df["neuron"] = df["neuron"].astype(int)
    df["layer_idx"] = df["layer"].apply(layer_name_to_index).astype(int)
    df["class_label"] = df[args.class_col].astype(str)

    if args.r_threshold is not None and "best_r" in df.columns:
        df = df[df["best_r"] >= args.r_threshold].copy()

    if args.p_threshold is not None and "best_p" in df.columns:
        df = df[df["best_p"] <= args.p_threshold].copy()

    if args.layers:
        keep_layers = set(parse_str_list(args.layers))
        df = df[df["layer"].astype(str).isin(keep_layers)].copy()

    if len(df) == 0:
        raise ValueError(
            "No neurons remain after filtering. Try lowering --r_threshold, "
            "removing --p_threshold, or checking --class_csv."
        )

    return df


def to_numpy(x: torch.Tensor) -> np.ndarray:
    return x.detach().cpu().numpy()


@dataclass
class LayerParams:
    layer_idx: int
    layer_name: str
    in_features: int
    out_features: int
    elementary_functions: List[str]
    scale_mlp: float
    base_weight: np.ndarray       # [out, in]
    C: np.ndarray                 # [M, out, in]
    D: np.ndarray                 # [M, out]
    ef_weights: np.ndarray        # [M]


def extract_layer_params(layer: SymbolicKANLinear, layer_idx: int) -> LayerParams:
    C = np.stack([to_numpy(p) for p in layer.ef_mlp_linears], axis=0)
    D = np.stack([to_numpy(p) for p in layer.ef_mlp_biases], axis=0)
    return LayerParams(
        layer_idx=layer_idx,
        layer_name=index_to_layer_name(layer_idx),
        in_features=layer.in_features,
        out_features=layer.out_features,
        elementary_functions=list(layer.elementary_functions),
        scale_mlp=float(layer.scale_mlp),
        base_weight=to_numpy(layer.base_weight),
        C=C,
        D=D,
        ef_weights=to_numpy(layer.ef_weights),
    )


def build_all_node_param_vectors(
    params: LayerParams,
    scale_param_vector: bool = True,
    include_ef_weight: bool = False,
    include_bias: bool = True,
    include_base: bool = True,
) -> np.ndarray:
    """
    Build parameter vector theta_{l,i} for every output neuron in one layer.

    By default, the elementary-function branch uses scale_mlp * c_{m,l,i,j}
    and scale_mlp * d_{l,m,i}, but it does NOT multiply by the elementary
    function prefactor w_{l,m}. This keeps the feature vector independent of
    the layer-shared elementary-function weight.

    Set include_ef_weight=True only if you want the old behavior:
    scale_mlp * w_{l,m} * c_{m,l,i,j} and scale_mlp * w_{l,m} * d_{l,m,i}.
    Set scale_param_vector=False to use raw C and D.
    """
    M, O, I = params.C.shape
    parts = []

    C = params.C.copy()
    D = params.D.copy()
    if scale_param_vector:
        ef_scale = np.full(M, params.scale_mlp, dtype=np.float64)
        if include_ef_weight:
            ef_scale = ef_scale * params.ef_weights.astype(np.float64)
        C = C * ef_scale[:, None, None]
        D = D * ef_scale[:, None]

    # [M, O, I] -> [O, M, I] -> [O, M*I]
    parts.append(np.transpose(C, (1, 0, 2)).reshape(O, M * I))

    if include_bias:
        # [M, O] -> [O, M]
        parts.append(D.T)

    if include_base:
        parts.append(params.base_weight.copy())

    return np.concatenate(parts, axis=1).astype(np.float64)


def zscore_by_reference(X: np.ndarray, reference: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    mu = reference.mean(axis=0, keepdims=True)
    sd = reference.std(axis=0, keepdims=True)
    return (X - mu) / (sd + eps)


def safe_pdist_stats(X: np.ndarray) -> Dict[str, float]:
    n = X.shape[0]
    if n == 0:
        return {
            "mean_l2_to_centroid": np.nan,
            "pairwise_l2_mean": np.nan,
            "pairwise_l2_std": np.nan,
            "pairwise_cosine_mean": np.nan,
            "pairwise_cosine_std": np.nan,
            "param_var_mean": np.nan,
        }

    centroid = X.mean(axis=0, keepdims=True)
    l2_to_centroid = np.linalg.norm(X - centroid, axis=1)

    result = {
        "mean_l2_to_centroid": float(np.mean(l2_to_centroid)),
        "param_var_mean": float(np.mean(np.var(X, axis=0))),
    }

    if n < 2:
        result.update({
            "pairwise_l2_mean": 0.0,
            "pairwise_l2_std": 0.0,
            "pairwise_cosine_mean": 1.0,
            "pairwise_cosine_std": 0.0,
        })
        return result

    d = pdist(X, metric="euclidean")
    result["pairwise_l2_mean"] = float(np.mean(d))
    result["pairwise_l2_std"] = float(np.std(d))

    norms = np.linalg.norm(X, axis=1, keepdims=True)
    Xn = X / (norms + 1e-12)
    sim = Xn @ Xn.T
    upper = sim[np.triu_indices(n, k=1)]
    result["pairwise_cosine_mean"] = float(np.mean(upper))
    result["pairwise_cosine_std"] = float(np.std(upper))
    return result


def mean_pairwise_corr_columns(A: np.ndarray, max_neurons: Optional[int] = None, seed: int = 0) -> Dict[str, float]:
    """Mean pairwise Pearson correlation among neuron activations in columns."""
    if A.ndim != 2:
        raise ValueError("A must be [N_samples, N_neurons]")
    n_neurons = A.shape[1]
    if n_neurons < 2:
        return {"functional_corr_mean": 1.0, "functional_corr_std": 0.0}

    if max_neurons is not None and n_neurons > max_neurons:
        rng = np.random.default_rng(seed)
        keep = rng.choice(n_neurons, size=max_neurons, replace=False)
        A = A[:, keep]
        n_neurons = A.shape[1]

    std = A.std(axis=0)
    valid = std > 1e-12
    A = A[:, valid]
    n_neurons = A.shape[1]
    if n_neurons < 2:
        return {"functional_corr_mean": np.nan, "functional_corr_std": np.nan}

    corr = np.corrcoef(A, rowvar=False)
    upper = corr[np.triu_indices(n_neurons, k=1)]
    upper = upper[np.isfinite(upper)]
    if len(upper) == 0:
        return {"functional_corr_mean": np.nan, "functional_corr_std": np.nan}

    return {
        "functional_corr_mean": float(np.mean(upper)),
        "functional_corr_std": float(np.std(upper)),
    }


# =============================================================================
# Dataset and activation extraction
# =============================================================================


def load_test_inputs_from_loader(args) -> np.ndarray:
    """
    Load test input a_test through your original MyKANnetLoader_2.load_dataset(opt).
    Only the input vector a is needed for contribution analysis.
    """
    try:
        import MyKANnetLoader_2
    except Exception as exc:
        raise ImportError(
            "Cannot import MyKANnetLoader_2. Either run this script in your original "
            "project environment, or use --no_dataset_contribution."
        ) from exc

    train_iter, val_iter, test_iter = MyKANnetLoader_2.load_dataset(args)

    a_list = []
    for batch in test_iter:
        if isinstance(batch, (list, tuple)):
            a = batch[0]
        else:
            a = batch
        a_list.append(a.detach().cpu())

    if len(a_list) == 0:
        raise RuntimeError("test_iter is empty; cannot compute data-driven contribution.")

    a_test = torch.cat(a_list, dim=0).numpy()
    input_dim = parse_int_list(args.layers_hidden)[0]
    a_test = a_test.reshape(-1, input_dim).astype(np.float32)
    return a_test


def sample_inputs(x: np.ndarray, max_samples: int, seed: int = 0) -> np.ndarray:
    if max_samples is None or max_samples <= 0 or x.shape[0] <= max_samples:
        return x
    rng = np.random.default_rng(seed)
    idx = rng.choice(x.shape[0], size=max_samples, replace=False)
    return x[idx]


def collect_layer_inputs_outputs(
    net: SymbolicKAN,
    x_np: np.ndarray,
    device: str,
    forward_batch: int = 512,
) -> Tuple[Dict[str, np.ndarray], Dict[str, np.ndarray]]:
    """
    For each layer l, collect h_{l-1} and h_l on the sampled dataset.
    Returns:
      layer_inputs['Layer1'] = raw input h_0
      layer_outputs['Layer1'] = h_1
      ...
    """
    layer_inputs = {index_to_layer_name(i): [] for i in range(len(net.layers))}
    layer_outputs = {index_to_layer_name(i): [] for i in range(len(net.layers))}

    net.eval()
    with torch.no_grad():
        for start in range(0, x_np.shape[0], forward_batch):
            end = min(start + forward_batch, x_np.shape[0])
            cur = torch.from_numpy(x_np[start:end]).float().to(device)

            for layer_idx, layer in enumerate(net.layers):
                layer_name = index_to_layer_name(layer_idx)
                layer_inputs[layer_name].append(cur.detach().cpu().numpy())
                cur = layer(cur)
                layer_outputs[layer_name].append(cur.detach().cpu().numpy())

    layer_inputs = {k: np.concatenate(v, axis=0) for k, v in layer_inputs.items()}
    layer_outputs = {k: np.concatenate(v, axis=0) for k, v in layer_outputs.items()}
    return layer_inputs, layer_outputs


# =============================================================================
# Group-level parameter analysis
# =============================================================================


def compute_class_mean_param_tensors(params: LayerParams, nodes: np.ndarray) -> Dict[str, np.ndarray]:
    C_sel = params.C[:, nodes, :]            # [M, K, I]
    D_sel = params.D[:, nodes]               # [M, K]
    B_sel = params.base_weight[nodes, :]     # [K, I]

    ef_scale = params.scale_mlp * params.ef_weights.astype(np.float64)
    weighted_C = C_sel * ef_scale[:, None, None]
    weighted_D = D_sel * ef_scale[:, None]

    return {
        "nodes": nodes.astype(np.int64),
        "C_mean": C_sel.mean(axis=1),
        "C_var": C_sel.var(axis=1),
        "D_mean": D_sel.mean(axis=1),
        "D_var": D_sel.var(axis=1),
        "weighted_C_mean": weighted_C.mean(axis=1),
        "weighted_C_var": weighted_C.var(axis=1),
        "weighted_D_mean": weighted_D.mean(axis=1),
        "weighted_D_var": weighted_D.var(axis=1),
        "base_weight_mean": B_sel.mean(axis=0),
        "base_weight_var": B_sel.var(axis=0),
        "ef_weights": params.ef_weights.copy(),
    }


def compute_ef_param_stats(params: LayerParams, nodes: np.ndarray, layer_name: str, class_label: str) -> List[Dict[str, Any]]:
    rows = []
    C_sel = params.C[:, nodes, :]
    D_sel = params.D[:, nodes]
    ef_scale = params.scale_mlp * params.ef_weights.astype(np.float64)

    for m, fname in enumerate(params.elementary_functions):
        C_m = C_sel[m]
        D_m = D_sel[m]
        weighted_C_m = C_m * ef_scale[m]
        weighted_D_m = D_m * ef_scale[m]
        rows.append({
            "layer": layer_name,
            "class_label": class_label,
            "n_nodes": int(len(nodes)),
            "ef_index": int(m),
            "ef_name": fname,
            "ef_weight": float(params.ef_weights[m]),
            "scale_mlp": float(params.scale_mlp),
            "mean_abs_c": float(np.mean(np.abs(C_m))),
            "std_abs_c": float(np.std(np.abs(C_m))),
            "mean_abs_weighted_c": float(np.mean(np.abs(weighted_C_m))),
            "std_abs_weighted_c": float(np.std(np.abs(weighted_C_m))),
            "mean_abs_d": float(np.mean(np.abs(D_m))),
            "std_abs_d": float(np.std(np.abs(D_m))),
            "mean_abs_weighted_d": float(np.mean(np.abs(weighted_D_m))),
            "std_abs_weighted_d": float(np.std(np.abs(weighted_D_m))),
            "var_weighted_c_mean": float(np.mean(np.var(weighted_C_m, axis=0))),
            "var_weighted_d": float(np.var(weighted_D_m)),
        })
    return rows


def compute_parameter_input_importance(
    params: LayerParams,
    nodes: np.ndarray,
    layer_name: str,
    class_label: str,
) -> pd.DataFrame:
    """
    Parameter-space input importance:

    I_{l,k,j} = sum_m |scale_mlp * w_{l,m}| mean_i |c_{m,l,i,j}|
                + mean_i |w^b_{l,i,j}|

    This is the direct implementation of the parameter-based index discussed
    in the analysis text.
    """
    C_sel = params.C[:, nodes, :]            # [M, K, I]
    B_sel = params.base_weight[nodes, :]     # [K, I]

    ef_scale_abs = np.abs(params.scale_mlp * params.ef_weights.astype(np.float64))
    ef_part_by_m = ef_scale_abs[:, None] * np.mean(np.abs(C_sel), axis=1)  # [M, I]
    ef_part_total = ef_part_by_m.sum(axis=0)                               # [I]
    base_part = np.mean(np.abs(B_sel), axis=0)                             # [I]
    total = ef_part_total + base_part

    rows = []
    for j in range(params.in_features):
        row = {
            "layer": layer_name,
            "class_label": class_label,
            "n_nodes": int(len(nodes)),
            "input_index": int(j),
            "importance_total": float(total[j]),
            "importance_ef_total": float(ef_part_total[j]),
            "importance_base": float(base_part[j]),
        }
        for m, fname in enumerate(params.elementary_functions):
            row[f"importance_ef_{m}_{fname}"] = float(ef_part_by_m[m, j])
        rows.append(row)
    return pd.DataFrame(rows)


# =============================================================================
# Inter-class difference analysis within the same layer
# =============================================================================


def _safe_class_mean_var(x: np.ndarray, class_axis: int, eps: float = 1e-12) -> Tuple[np.ndarray, np.ndarray]:
    """Mean and variance along the class/neuron axis with float64 precision."""
    x = np.asarray(x, dtype=np.float64)
    if x.shape[class_axis] == 0:
        raise ValueError("Cannot compute class statistics for an empty class.")
    return np.mean(x, axis=class_axis), np.var(x, axis=class_axis) + eps


def _standardized_difference(mu_a: np.ndarray, mu_b: np.ndarray, var_a: np.ndarray, var_b: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """
    Cohen-d-like standardized mean difference for parameter dimensions.

    z_q = (mu_a_q - mu_b_q) / sqrt(0.5 * (var_a_q + var_b_q) + eps)

    This helps distinguish a large raw difference from a difference that is
    large relative to within-class dispersion.
    """
    return (mu_a - mu_b) / np.sqrt(0.5 * (var_a + var_b) + eps)


def _array_l2_stats(diff: np.ndarray, z: np.ndarray) -> Dict[str, float]:
    diff = np.asarray(diff, dtype=np.float64)
    z = np.asarray(z, dtype=np.float64)
    raw_sq = float(np.sum(diff ** 2))
    z_sq = float(np.sum(z ** 2))
    n_dim = int(diff.size)
    return {
        "n_dimensions": n_dim,
        "raw_l2": float(np.sqrt(raw_sq)),
        "raw_l2_sq": raw_sq,
        "raw_rms_diff": float(np.sqrt(raw_sq / max(n_dim, 1))),
        "raw_mean_abs_diff": float(np.mean(np.abs(diff))) if n_dim > 0 else np.nan,
        "standardized_l2": float(np.sqrt(z_sq)),
        "standardized_l2_sq": z_sq,
        "standardized_rms_diff": float(np.sqrt(z_sq / max(n_dim, 1))),
        "standardized_mean_abs_diff": float(np.mean(np.abs(z))) if n_dim > 0 else np.nan,
    }


def compute_inter_class_parameter_differences(
    params: LayerParams,
    nodes_a: np.ndarray,
    nodes_b: np.ndarray,
    layer_name: str,
    class_a: str,
    class_b: str,
    include_ef_weight: bool = True,
    top_dims: int = 30,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:
    """
    Decompose same-layer inter-class parameter differences.

    The previous inter_class_distance.csv only reports centroid distance. This
    function explains what produces that distance by decomposing class-pair
    differences into:
      1) parameter blocks: each elementary-function C branch, each D bias, base_weight;
      2) elementary functions: C_m + D_m for each elementary function;
      3) input dimensions: all C_{m,j} plus base_weight_j;
      4) individual parameter dimensions with the largest standardized effect.

    Raw differences answer "where is the centroid distance large?".
    Standardized differences answer "where is the difference large relative to
    within-class variability?".
    """
    nodes_a = np.asarray(nodes_a, dtype=np.int64)
    nodes_b = np.asarray(nodes_b, dtype=np.int64)
    M, O, I = params.C.shape

    C_a = params.C[:, nodes_a, :]              # [M, Ka, I]
    C_b = params.C[:, nodes_b, :]              # [M, Kb, I]
    D_a = params.D[:, nodes_a]                 # [M, Ka]
    D_b = params.D[:, nodes_b]                 # [M, Kb]
    B_a = params.base_weight[nodes_a, :]       # [Ka, I]
    B_b = params.base_weight[nodes_b, :]       # [Kb, I]

    C_mu_a, C_var_a = _safe_class_mean_var(C_a, class_axis=1)
    C_mu_b, C_var_b = _safe_class_mean_var(C_b, class_axis=1)
    D_mu_a, D_var_a = _safe_class_mean_var(D_a, class_axis=1)
    D_mu_b, D_var_b = _safe_class_mean_var(D_b, class_axis=1)
    B_mu_a, B_var_a = _safe_class_mean_var(B_a, class_axis=0)
    B_mu_b, B_var_b = _safe_class_mean_var(B_b, class_axis=0)

    # Use effective branch scaling by default because it reflects the actual
    # layer computation. ef_weights are shared within a layer, so they do not
    # themselves create class differences, but they do change the relative
    # contribution of each elementary-function branch to the output.
    if include_ef_weight:
        ef_scale = params.scale_mlp * params.ef_weights.astype(np.float64)
    else:
        ef_scale = np.full(M, params.scale_mlp, dtype=np.float64)

    C_mu_a_eff = C_mu_a * ef_scale[:, None]
    C_mu_b_eff = C_mu_b * ef_scale[:, None]
    C_var_a_eff = C_var_a * (ef_scale[:, None] ** 2)
    C_var_b_eff = C_var_b * (ef_scale[:, None] ** 2)
    D_mu_a_eff = D_mu_a * ef_scale
    D_mu_b_eff = D_mu_b * ef_scale
    D_var_a_eff = D_var_a * (ef_scale ** 2)
    D_var_b_eff = D_var_b * (ef_scale ** 2)

    dC = C_mu_a_eff - C_mu_b_eff               # [M, I]
    dD = D_mu_a_eff - D_mu_b_eff               # [M]
    dB = B_mu_a - B_mu_b                       # [I]
    zC = _standardized_difference(C_mu_a_eff, C_mu_b_eff, C_var_a_eff, C_var_b_eff)
    zD = _standardized_difference(D_mu_a_eff, D_mu_b_eff, D_var_a_eff, D_var_b_eff)
    zB = _standardized_difference(B_mu_a, B_mu_b, B_var_a, B_var_b)

    total_raw_sq = float(np.sum(dC ** 2) + np.sum(dD ** 2) + np.sum(dB ** 2))
    total_z_sq = float(np.sum(zC ** 2) + np.sum(zD ** 2) + np.sum(zB ** 2))
    eps = 1e-12

    block_rows: List[Dict[str, Any]] = []

    def add_block(block_name: str, block_type: str, diff: np.ndarray, z: np.ndarray, ef_index: Optional[int] = None, ef_name: str = ""):
        st = _array_l2_stats(diff, z)
        row = {
            "layer": layer_name,
            "class_label_a": str(class_a),
            "class_label_b": str(class_b),
            "n_nodes_a": int(len(nodes_a)),
            "n_nodes_b": int(len(nodes_b)),
            "block": block_name,
            "block_type": block_type,
            "ef_index": np.nan if ef_index is None else int(ef_index),
            "ef_name": ef_name,
            "include_ef_weight": bool(include_ef_weight),
            **st,
        }
        row["raw_contribution_ratio"] = float(st["raw_l2_sq"] / (total_raw_sq + eps))
        row["standardized_contribution_ratio"] = float(st["standardized_l2_sq"] / (total_z_sq + eps))
        block_rows.append(row)

    for m, fname in enumerate(params.elementary_functions):
        add_block(f"{fname}_C", "elementary_C", dC[m], zC[m], ef_index=m, ef_name=fname)
        add_block(f"{fname}_D", "elementary_D", np.asarray([dD[m]]), np.asarray([zD[m]]), ef_index=m, ef_name=fname)
    add_block("base_weight", "base_weight", dB, zB, ef_index=None, ef_name="base")

    ef_rows: List[Dict[str, Any]] = []
    ef_raw_scores = np.sum(dC ** 2, axis=1) + dD ** 2
    ef_z_scores = np.sum(zC ** 2, axis=1) + zD ** 2
    ef_raw_total = float(np.sum(ef_raw_scores))
    ef_z_total = float(np.sum(ef_z_scores))
    for m, fname in enumerate(params.elementary_functions):
        ef_rows.append({
            "layer": layer_name,
            "class_label_a": str(class_a),
            "class_label_b": str(class_b),
            "n_nodes_a": int(len(nodes_a)),
            "n_nodes_b": int(len(nodes_b)),
            "ef_index": int(m),
            "ef_name": fname,
            "ef_scale_used": float(ef_scale[m]),
            "C_raw_l2_sq": float(np.sum(dC[m] ** 2)),
            "D_raw_l2_sq": float(dD[m] ** 2),
            "ef_raw_l2_sq": float(ef_raw_scores[m]),
            "ef_raw_l2": float(np.sqrt(ef_raw_scores[m])),
            "ef_raw_contribution_ratio_among_ef": float(ef_raw_scores[m] / (ef_raw_total + eps)),
            "ef_raw_contribution_ratio_total": float(ef_raw_scores[m] / (total_raw_sq + eps)),
            "C_standardized_l2_sq": float(np.sum(zC[m] ** 2)),
            "D_standardized_l2_sq": float(zD[m] ** 2),
            "ef_standardized_l2_sq": float(ef_z_scores[m]),
            "ef_standardized_l2": float(np.sqrt(ef_z_scores[m])),
            "ef_standardized_contribution_ratio_among_ef": float(ef_z_scores[m] / (ef_z_total + eps)),
            "ef_standardized_contribution_ratio_total": float(ef_z_scores[m] / (total_z_sq + eps)),
            "mean_abs_C_diff": float(np.mean(np.abs(dC[m]))),
            "mean_abs_C_standardized_diff": float(np.mean(np.abs(zC[m]))),
            "D_diff": float(dD[m]),
            "D_standardized_diff": float(zD[m]),
        })

    input_rows: List[Dict[str, Any]] = []
    input_raw_scores = np.sum(dC ** 2, axis=0) + dB ** 2
    input_z_scores = np.sum(zC ** 2, axis=0) + zB ** 2
    input_raw_total = float(np.sum(input_raw_scores))
    input_z_total = float(np.sum(input_z_scores))
    for j in range(I):
        top_m_raw = int(np.argmax(dC[:, j] ** 2)) if M > 0 else -1
        top_m_z = int(np.argmax(zC[:, j] ** 2)) if M > 0 else -1
        input_rows.append({
            "layer": layer_name,
            "class_label_a": str(class_a),
            "class_label_b": str(class_b),
            "n_nodes_a": int(len(nodes_a)),
            "n_nodes_b": int(len(nodes_b)),
            "input_index": int(j),
            "input_raw_l2_sq": float(input_raw_scores[j]),
            "input_raw_l2": float(np.sqrt(input_raw_scores[j])),
            "input_raw_contribution_ratio": float(input_raw_scores[j] / (input_raw_total + eps)),
            "input_standardized_l2_sq": float(input_z_scores[j]),
            "input_standardized_l2": float(np.sqrt(input_z_scores[j])),
            "input_standardized_contribution_ratio": float(input_z_scores[j] / (input_z_total + eps)),
            "base_diff": float(dB[j]),
            "base_standardized_diff": float(zB[j]),
            "ef_C_raw_l2_sq": float(np.sum(dC[:, j] ** 2)),
            "ef_C_standardized_l2_sq": float(np.sum(zC[:, j] ** 2)),
            "top_ef_by_raw_input_diff": params.elementary_functions[top_m_raw] if top_m_raw >= 0 else "",
            "top_ef_by_standardized_input_diff": params.elementary_functions[top_m_z] if top_m_z >= 0 else "",
        })

    dim_rows: List[Dict[str, Any]] = []
    # Candidate parameter dimensions. Rank by abs standardized difference; keep
    # top_dims to avoid huge CSVs for wide layers.
    candidates: List[Dict[str, Any]] = []
    for m, fname in enumerate(params.elementary_functions):
        for j in range(I):
            candidates.append({
                "parameter_block": f"{fname}_C",
                "parameter_type": "elementary_C",
                "ef_index": int(m),
                "ef_name": fname,
                "input_index": int(j),
                "mean_a": float(C_mu_a_eff[m, j]),
                "mean_b": float(C_mu_b_eff[m, j]),
                "raw_diff": float(dC[m, j]),
                "standardized_diff": float(zC[m, j]),
            })
        candidates.append({
            "parameter_block": f"{fname}_D",
            "parameter_type": "elementary_D",
            "ef_index": int(m),
            "ef_name": fname,
            "input_index": np.nan,
            "mean_a": float(D_mu_a_eff[m]),
            "mean_b": float(D_mu_b_eff[m]),
            "raw_diff": float(dD[m]),
            "standardized_diff": float(zD[m]),
        })
    for j in range(I):
        candidates.append({
            "parameter_block": "base_weight",
            "parameter_type": "base_weight",
            "ef_index": np.nan,
            "ef_name": "base",
            "input_index": int(j),
            "mean_a": float(B_mu_a[j]),
            "mean_b": float(B_mu_b[j]),
            "raw_diff": float(dB[j]),
            "standardized_diff": float(zB[j]),
        })

    candidates.sort(key=lambda r: abs(r["standardized_diff"]), reverse=True)
    for rank, row in enumerate(candidates[:max(0, int(top_dims))], start=1):
        row = dict(row)
        row.update({
            "layer": layer_name,
            "class_label_a": str(class_a),
            "class_label_b": str(class_b),
            "n_nodes_a": int(len(nodes_a)),
            "n_nodes_b": int(len(nodes_b)),
            "rank_by_abs_standardized_diff": int(rank),
            "abs_raw_diff": float(abs(row["raw_diff"])),
            "abs_standardized_diff": float(abs(row["standardized_diff"])),
        })
        dim_rows.append(row)

    summary = {
        "layer": layer_name,
        "class_label_a": str(class_a),
        "class_label_b": str(class_b),
        "n_nodes_a": int(len(nodes_a)),
        "n_nodes_b": int(len(nodes_b)),
        "include_ef_weight": bool(include_ef_weight),
        "total_raw_l2": float(np.sqrt(total_raw_sq)),
        "total_raw_l2_sq": total_raw_sq,
        "total_standardized_l2": float(np.sqrt(total_z_sq)),
        "total_standardized_l2_sq": total_z_sq,
        "base_raw_contribution_ratio": float(np.sum(dB ** 2) / (total_raw_sq + eps)),
        "ef_raw_contribution_ratio": float((np.sum(dC ** 2) + np.sum(dD ** 2)) / (total_raw_sq + eps)),
        "base_standardized_contribution_ratio": float(np.sum(zB ** 2) / (total_z_sq + eps)),
        "ef_standardized_contribution_ratio": float((np.sum(zC ** 2) + np.sum(zD ** 2)) / (total_z_sq + eps)),
        "top_block_by_raw_ratio": max(block_rows, key=lambda r: r["raw_contribution_ratio"])["block"] if block_rows else "",
        "top_block_raw_ratio": float(max((r["raw_contribution_ratio"] for r in block_rows), default=np.nan)),
        "top_block_by_standardized_ratio": max(block_rows, key=lambda r: r["standardized_contribution_ratio"])["block"] if block_rows else "",
        "top_block_standardized_ratio": float(max((r["standardized_contribution_ratio"] for r in block_rows), default=np.nan)),
        "top_ef_by_raw_total": params.elementary_functions[int(np.argmax(ef_raw_scores))] if M > 0 else "",
        "top_ef_raw_total_ratio": float(np.max(ef_raw_scores) / (ef_raw_total + eps)) if M > 0 else np.nan,
        "top_ef_by_standardized_total": params.elementary_functions[int(np.argmax(ef_z_scores))] if M > 0 else "",
        "top_ef_standardized_total_ratio": float(np.max(ef_z_scores) / (ef_z_total + eps)) if M > 0 else np.nan,
        "top_input_by_raw_difference": int(np.argmax(input_raw_scores)) if I > 0 else -1,
        "top_input_raw_difference_ratio": float(np.max(input_raw_scores) / (input_raw_total + eps)) if I > 0 else np.nan,
        "top_input_by_standardized_difference": int(np.argmax(input_z_scores)) if I > 0 else -1,
        "top_input_standardized_difference_ratio": float(np.max(input_z_scores) / (input_z_total + eps)) if I > 0 else np.nan,
    }

    return block_rows, ef_rows, input_rows, dim_rows, summary


def compute_pairwise_data_difference_tables(
    data_summary_df: pd.DataFrame,
    input_data_df_all: pd.DataFrame,
    ef_data_df_all: pd.DataFrame,
    top_inputs: int = 30,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Compare already-computed data-driven contributions between classes."""
    summary_rows: List[Dict[str, Any]] = []
    input_rows: List[Dict[str, Any]] = []
    ef_rows: List[Dict[str, Any]] = []

    if data_summary_df is not None and len(data_summary_df) > 0:
        value_cols = [
            "base_output_mean_abs",
            "ef_output_mean_abs_sum",
            "ef_to_base_abs_ratio",
            "functional_corr_mean",
        ]
        for layer_name, g in data_summary_df.groupby("layer"):
            labels = sorted(g["class_label"].astype(str).unique())
            by_label = {str(row["class_label"]): row for _, row in g.iterrows()}
            for ia in range(len(labels)):
                for ib in range(ia + 1, len(labels)):
                    a, b = labels[ia], labels[ib]
                    ra, rb = by_label[a], by_label[b]
                    row = {
                        "layer": layer_name,
                        "class_label_a": a,
                        "class_label_b": b,
                        "n_nodes_a": int(ra.get("n_nodes", np.nan)),
                        "n_nodes_b": int(rb.get("n_nodes", np.nan)),
                    }
                    for col in value_cols:
                        if col in data_summary_df.columns:
                            va = float(ra[col]) if pd.notna(ra[col]) else np.nan
                            vb = float(rb[col]) if pd.notna(rb[col]) else np.nan
                            row[f"{col}_a"] = va
                            row[f"{col}_b"] = vb
                            row[f"{col}_diff_a_minus_b"] = float(va - vb) if np.isfinite(va) and np.isfinite(vb) else np.nan
                            row[f"{col}_abs_diff"] = float(abs(va - vb)) if np.isfinite(va) and np.isfinite(vb) else np.nan
                    summary_rows.append(row)

    if input_data_df_all is not None and len(input_data_df_all) > 0:
        value_col = "importance_total_data_weighted"
        if value_col in input_data_df_all.columns:
            for layer_name, g_layer in input_data_df_all.groupby("layer"):
                labels = sorted(g_layer["class_label"].astype(str).unique())
                for ia in range(len(labels)):
                    for ib in range(ia + 1, len(labels)):
                        a, b = labels[ia], labels[ib]
                        ga = g_layer[g_layer["class_label"].astype(str) == a].set_index("input_index")
                        gb = g_layer[g_layer["class_label"].astype(str) == b].set_index("input_index")
                        common = sorted(set(ga.index).intersection(set(gb.index)))
                        pair_rows = []
                        for j in common:
                            va = float(ga.loc[j, value_col])
                            vb = float(gb.loc[j, value_col])
                            pair_rows.append({
                                "layer": layer_name,
                                "class_label_a": a,
                                "class_label_b": b,
                                "input_index": int(j),
                                "importance_total_data_weighted_a": va,
                                "importance_total_data_weighted_b": vb,
                                "data_weighted_input_diff_a_minus_b": float(va - vb),
                                "data_weighted_input_abs_diff": float(abs(va - vb)),
                            })
                        pair_rows.sort(key=lambda r: r["data_weighted_input_abs_diff"], reverse=True)
                        for rank, row in enumerate(pair_rows[:max(0, int(top_inputs))], start=1):
                            row["rank_by_data_weighted_input_abs_diff"] = int(rank)
                            input_rows.append(row)

    if ef_data_df_all is not None and len(ef_data_df_all) > 0:
        value_col = "mean_abs_actual_output"
        if value_col in ef_data_df_all.columns:
            for layer_name, g_layer in ef_data_df_all.groupby("layer"):
                labels = sorted(g_layer["class_label"].astype(str).unique())
                for ia in range(len(labels)):
                    for ib in range(ia + 1, len(labels)):
                        a, b = labels[ia], labels[ib]
                        ga = g_layer[g_layer["class_label"].astype(str) == a].set_index("ef_index")
                        gb = g_layer[g_layer["class_label"].astype(str) == b].set_index("ef_index")
                        common = sorted(set(ga.index).intersection(set(gb.index)))
                        for m in common:
                            va = float(ga.loc[m, value_col])
                            vb = float(gb.loc[m, value_col])
                            ef_name = str(ga.loc[m, "ef_name"]) if "ef_name" in ga.columns else str(m)
                            ef_rows.append({
                                "layer": layer_name,
                                "class_label_a": a,
                                "class_label_b": b,
                                "ef_index": int(m),
                                "ef_name": ef_name,
                                "mean_abs_actual_output_a": va,
                                "mean_abs_actual_output_b": vb,
                                "actual_output_diff_a_minus_b": float(va - vb),
                                "actual_output_abs_diff": float(abs(va - vb)),
                            })

    return pd.DataFrame(summary_rows), pd.DataFrame(input_rows), pd.DataFrame(ef_rows)


# =============================================================================
# Data-driven contribution analysis
# =============================================================================


def compute_data_contribution_for_group(
    layer: SymbolicKANLinear,
    params: LayerParams,
    nodes: np.ndarray,
    x_prev_np: np.ndarray,
    h_out_np: Optional[np.ndarray],
    layer_name: str,
    class_label: str,
    device: str,
) -> Tuple[Dict[str, Any], pd.DataFrame, pd.DataFrame]:
    """
    Estimate actual contribution on data.

    Returns:
      summary_row:
        actual elementary-function output magnitude and base output magnitude
      input_df:
        data-weighted input importance per input dimension
      ef_df:
        actual contribution per elementary function
    """
    nodes_t = torch.as_tensor(nodes, dtype=torch.long, device=device)
    x_prev = torch.from_numpy(x_prev_np).float().to(device)

    with torch.no_grad():
        base_act = layer.base_activation(x_prev)                  # [N, I]
        x_abs_mean = torch.mean(torch.abs(x_prev), dim=0)          # [I]
        base_act_abs_mean = torch.mean(torch.abs(base_act), dim=0) # [I]

        base_weight_sel = layer.base_weight.index_select(0, nodes_t)  # [K, I]
        base_output = F.linear(base_act, base_weight_sel)             # [N, K]
        base_output_mean_abs = torch.mean(torch.abs(base_output)).item()

        base_input_importance = (
            torch.mean(torch.abs(base_weight_sel), dim=0) * base_act_abs_mean
        )  # [I]

        ef_rows = []
        ef_input_total = torch.zeros(params.in_features, device=device)
        ef_output_abs_values = []

        for m, fname in enumerate(params.elementary_functions):
            C_m_sel = layer.ef_mlp_linears[m].index_select(0, nodes_t)  # [K, I]
            D_m_sel = layer.ef_mlp_biases[m].index_select(0, nodes_t)   # [K]
            ef_weight_m = layer.ef_weights[m]

            z = F.linear(x_prev, C_m_sel, D_m_sel)                     # [N, K]
            y = SUPPORTED_ELEMENTARY_FUNCTIONS[fname](z) * ef_weight_m * layer.scale_mlp

            y_abs_mean = torch.mean(torch.abs(y)).item()
            y_mean = torch.mean(y).item()
            y_std = torch.std(y).item()
            ef_output_abs_values.append(y_abs_mean)

            # Data-weighted approximate input importance of elementary branch:
            # |scale_mlp * w_m| * mean_i |c_mij| * mean_n |h_{l-1,j}|
            ef_input_m = (
                torch.abs(ef_weight_m * layer.scale_mlp)
                * torch.mean(torch.abs(C_m_sel), dim=0)
                * x_abs_mean
            )
            ef_input_total += ef_input_m

            ef_rows.append({
                "layer": layer_name,
                "class_label": class_label,
                "n_nodes": int(len(nodes)),
                "ef_index": int(m),
                "ef_name": fname,
                "ef_weight": float(ef_weight_m.detach().cpu()),
                "mean_abs_actual_output": float(y_abs_mean),
                "mean_actual_output": float(y_mean),
                "std_actual_output": float(y_std),
                "data_weighted_input_importance_sum": float(torch.sum(ef_input_m).detach().cpu()),
                "data_weighted_input_importance_mean": float(torch.mean(ef_input_m).detach().cpu()),
            })

        ef_total_output_mean_abs_sum = float(np.sum(ef_output_abs_values))

        input_total = ef_input_total + base_input_importance
        input_rows = []
        for j in range(params.in_features):
            input_rows.append({
                "layer": layer_name,
                "class_label": class_label,
                "n_nodes": int(len(nodes)),
                "input_index": int(j),
                "importance_total_data_weighted": float(input_total[j].detach().cpu()),
                "importance_ef_data_weighted": float(ef_input_total[j].detach().cpu()),
                "importance_base_data_weighted": float(base_input_importance[j].detach().cpu()),
                "mean_abs_input": float(x_abs_mean[j].detach().cpu()),
                "mean_abs_base_activation_input": float(base_act_abs_mean[j].detach().cpu()),
            })

        functional_stats = {"functional_corr_mean": np.nan, "functional_corr_std": np.nan}
        if h_out_np is not None:
            h_group = h_out_np[:, nodes]
            functional_stats = mean_pairwise_corr_columns(h_group, max_neurons=300)

        summary_row = {
            "layer": layer_name,
            "class_label": class_label,
            "n_nodes": int(len(nodes)),
            "n_samples": int(x_prev_np.shape[0]),
            "base_output_mean_abs": float(base_output_mean_abs),
            "ef_output_mean_abs_sum": float(ef_total_output_mean_abs_sum),
            "ef_to_base_abs_ratio": float(ef_total_output_mean_abs_sum / (base_output_mean_abs + 1e-12)),
            "top_ef_by_actual_output": str(ef_rows[int(np.argmax(ef_output_abs_values))]["ef_name"]),
            "top_ef_actual_output": float(np.max(ef_output_abs_values)),
            **functional_stats,
        }

    return summary_row, pd.DataFrame(input_rows), pd.DataFrame(ef_rows)


# =============================================================================
# Plotting
# =============================================================================


def plot_inter_class_heatmap(layer_name: str, labels: List[str], mat: np.ndarray, save_path: str):
    if len(labels) == 0:
        return
    fig_w = max(6, 0.55 * len(labels) + 3)
    fig_h = max(5, 0.50 * len(labels) + 2)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    im = ax.imshow(mat, cmap="viridis")
    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.set_yticklabels(labels)
    ax.set_title(f"{layer_name}: inter-class centroid distance")
    ax.set_xlabel("Class label")
    ax.set_ylabel("Class label")
    for i in range(len(labels)):
        for j in range(len(labels)):
            ax.text(j, i, f"{mat[i, j]:.2f}", ha="center", va="center", fontsize=8)
    fig.colorbar(im, ax=ax, label="Euclidean distance")
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_top_inputs(df: pd.DataFrame, value_col: str, title: str, save_path: str, top_k: int = 30):
    if len(df) == 0 or value_col not in df.columns:
        return
    top_df = df.sort_values(value_col, ascending=False).head(top_k)
    labels = [str(int(x)) for x in top_df["input_index"].values]
    vals = top_df[value_col].values

    plt.figure(figsize=(max(8, 0.35 * len(labels) + 3), 4.8))
    plt.bar(np.arange(len(vals)), vals)
    plt.xticks(np.arange(len(vals)), labels, rotation=60, ha="right")
    plt.xlabel("Input node index j")
    plt.ylabel(value_col)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()


def plot_ef_bars(df: pd.DataFrame, value_col: str, title: str, save_path: str):
    if len(df) == 0 or value_col not in df.columns:
        return
    df = df.sort_values("ef_index")
    labels = df["ef_name"].astype(str).tolist()
    vals = df[value_col].values

    plt.figure(figsize=(max(7, 0.6 * len(labels) + 2), 4.5))
    plt.bar(np.arange(len(vals)), vals)
    plt.xticks(np.arange(len(vals)), labels, rotation=45, ha="right")
    plt.ylabel(value_col)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()



def plot_top_categories(df: pd.DataFrame, label_col: str, value_col: str, title: str, save_path: str, top_k: int = 20):
    if len(df) == 0 or label_col not in df.columns or value_col not in df.columns:
        return
    top_df = df.sort_values(value_col, ascending=False).head(top_k)
    labels = top_df[label_col].astype(str).tolist()
    vals = top_df[value_col].values

    plt.figure(figsize=(max(8, 0.45 * len(labels) + 3), 4.8))
    plt.bar(np.arange(len(vals)), vals)
    plt.xticks(np.arange(len(vals)), labels, rotation=60, ha="right")
    plt.ylabel(value_col)
    plt.title(title)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()


# =============================================================================
# Main analysis
# =============================================================================


def analyze(args):
    ensure_dir(args.save_dir)
    fig_dir = ensure_dir(os.path.join(args.save_dir, "figures"))
    npz_dir = ensure_dir(os.path.join(args.save_dir, "class_mean_params"))

    device = "cuda" if torch.cuda.is_available() and not args.cpu else "cpu"
    print(f"Using device: {device}")

    print("\n===== Loading trained SymbolicKAN =====")
    net = load_symbolic_kan_model(args, device=device)

    print("\n===== Loading neuron classification CSV =====")
    class_df = load_classification_df(args)
    print(f"Loaded classified neurons: {len(class_df)}")
    print(class_df.groupby(["layer", "class_label"]).size().rename("count"))

    class_df.to_csv(os.path.join(args.save_dir, "filtered_classification_used.csv"), index=False, encoding="utf-8-sig")

    print("\n===== Extracting layer parameters =====")
    layer_params_map: Dict[str, LayerParams] = {}
    all_vectors_map: Dict[str, np.ndarray] = {}
    vector_reference_map: Dict[str, np.ndarray] = {}

    for layer_idx, layer in enumerate(net.layers):
        layer_name = index_to_layer_name(layer_idx)
        params = extract_layer_params(layer, layer_idx)
        layer_params_map[layer_name] = params
        all_vec = build_all_node_param_vectors(
            params,
            scale_param_vector=args.scale_param_vector,
            include_ef_weight=args.include_ef_weight_in_param_vector,
            include_bias=not args.exclude_bias_from_vector,
            include_base=not args.exclude_base_from_vector,
        )
        all_vectors_map[layer_name] = all_vec
        vector_reference_map[layer_name] = all_vec
        print(f"{layer_name}: C={params.C.shape}, D={params.D.shape}, base_weight={params.base_weight.shape}, vector={all_vec.shape}")

    # Optional dataset-driven contribution analysis.
    layer_inputs = None
    layer_outputs = None
    if not args.no_dataset_contribution:
        print("\n===== Loading test data for contribution analysis =====")
        try:
            x_test = load_test_inputs_from_loader(args)
            x_test = sample_inputs(x_test, max_samples=args.max_contribution_samples, seed=args.seed)
            print(f"Contribution samples: {x_test.shape}")

            print("\n===== Collecting h_{l-1} and h_l for each layer =====")
            layer_inputs, layer_outputs = collect_layer_inputs_outputs(
                net=net,
                x_np=x_test,
                device=device,
                forward_batch=args.forward_batch,
            )
            for ln in layer_inputs.keys():
                print(f"{ln}: input={layer_inputs[ln].shape}, output={layer_outputs[ln].shape}")
        except Exception as exc:
            if args.strict_dataset_contribution:
                raise
            warnings.warn(
                "Dataset-driven contribution analysis was skipped because data loading failed. "
                f"Reason: {repr(exc)}\n"
                "Parameter-space analysis will still be saved. "
                "Use --no_dataset_contribution to silence this warning."
            )
            layer_inputs = None
            layer_outputs = None

    class_summary_rows = []
    ef_param_rows = []
    input_param_dfs = []
    input_data_dfs = []
    data_summary_rows = []
    ef_data_dfs = []
    centroid_rows = []

    # Inter-class difference decomposition, filled after same-class groups
    # are identified and the class-wise outputs above are available.
    inter_class_block_rows = []
    inter_class_ef_rows = []
    inter_class_input_rows = []
    inter_class_top_dim_rows = []
    inter_class_summary_rows = []

    print("\n===== Analyzing same-layer same-class neuron groups =====")
    grouped = class_df.groupby(["layer", "class_label"], sort=True)

    # Store centroids and valid node sets for inter-class comparison.
    centroids_by_layer: Dict[str, Dict[str, np.ndarray]] = {}
    nodes_by_layer_class: Dict[str, Dict[str, np.ndarray]] = {}

    for (layer_name, class_label), g in grouped:
        if layer_name not in layer_params_map:
            warnings.warn(f"Skip {layer_name}, not present in model layers.")
            continue

        params = layer_params_map[layer_name]
        nodes = np.sort(g["neuron"].astype(int).unique())
        nodes = nodes[(nodes >= 0) & (nodes < params.out_features)]
        if len(nodes) == 0:
            warnings.warn(f"Skip {layer_name}/{class_label}: no valid neuron index.")
            continue
        if len(nodes) < args.min_group_size:
            print(f"Skip {layer_name}/{class_label}: n_nodes={len(nodes)} < min_group_size={args.min_group_size}")
            continue

        all_vec = all_vectors_map[layer_name]
        X = all_vec[nodes]
        if args.standardize_vectors:
            X = zscore_by_reference(X, vector_reference_map[layer_name])

        stats = safe_pdist_stats(X)
        centroid = X.mean(axis=0)
        centroids_by_layer.setdefault(layer_name, {})[str(class_label)] = centroid
        nodes_by_layer_class.setdefault(layer_name, {})[str(class_label)] = nodes.copy()

        # Basic parameter magnitudes.
        C_sel = params.C[:, nodes, :]
        D_sel = params.D[:, nodes]
        B_sel = params.base_weight[nodes, :]
        ef_scale = params.scale_mlp * params.ef_weights.astype(np.float64)
        weighted_C_sel = C_sel * ef_scale[:, None, None]
        weighted_D_sel = D_sel * ef_scale[:, None]

        rsa_stats = {}
        if "best_r" in g.columns:
            rsa_stats.update({
                "mean_best_r": float(g["best_r"].mean()),
                "std_best_r": float(g["best_r"].std(ddof=0)),
                "max_best_r": float(g["best_r"].max()),
                "min_best_r": float(g["best_r"].min()),
            })
        if "best_p" in g.columns:
            rsa_stats.update({
                "mean_best_p": float(g["best_p"].mean()),
                "median_best_p": float(g["best_p"].median()),
            })

        ef_strength_by_m = np.mean(np.abs(weighted_C_sel), axis=(1, 2))
        top_m = int(np.argmax(ef_strength_by_m))

        summary = {
            "layer": layer_name,
            "layer_idx": int(params.layer_idx),
            "class_label": str(class_label),
            "n_nodes": int(len(nodes)),
            "neurons": ";".join(map(str, nodes.tolist())),
            "in_features": int(params.in_features),
            "out_features": int(params.out_features),
            "param_vector_dim": int(X.shape[1]),
            "param_norm_mean": float(np.linalg.norm(X, axis=1).mean()),
            "param_norm_std": float(np.linalg.norm(X, axis=1).std()),
            "mean_abs_c": float(np.mean(np.abs(C_sel))),
            "mean_abs_weighted_c": float(np.mean(np.abs(weighted_C_sel))),
            "mean_abs_d": float(np.mean(np.abs(D_sel))),
            "mean_abs_weighted_d": float(np.mean(np.abs(weighted_D_sel))),
            "mean_abs_base_weight": float(np.mean(np.abs(B_sel))),
            "top_ef_by_weighted_c": params.elementary_functions[top_m],
            "top_ef_weighted_c_mean_abs": float(ef_strength_by_m[top_m]),
            **rsa_stats,
            **stats,
        }

        class_summary_rows.append(summary)

        # Save class mean and variance tensors.
        tensor_stats = compute_class_mean_param_tensors(params, nodes)
        npz_name = f"{sanitize_name(layer_name)}__{sanitize_name(class_label)}__mean_params.npz"
        np.savez_compressed(os.path.join(npz_dir, npz_name), **tensor_stats)

        # Detailed elementary-function parameter stats.
        ef_param_rows.extend(compute_ef_param_stats(params, nodes, layer_name, str(class_label)))

        # Parameter-based input importance.
        input_param_df = compute_parameter_input_importance(params, nodes, layer_name, str(class_label))
        input_param_dfs.append(input_param_df)

        # Data-driven contribution.
        if layer_inputs is not None and layer_outputs is not None and layer_name in layer_inputs:
            data_summary, input_data_df, ef_data_df = compute_data_contribution_for_group(
                layer=net.layers[params.layer_idx],
                params=params,
                nodes=nodes,
                x_prev_np=layer_inputs[layer_name],
                h_out_np=layer_outputs[layer_name],
                layer_name=layer_name,
                class_label=str(class_label),
                device=device,
            )
            data_summary_rows.append(data_summary)
            input_data_dfs.append(input_data_df)
            ef_data_dfs.append(ef_data_df)

        centroid_rows.append({
            "layer": layer_name,
            "class_label": str(class_label),
            "centroid_norm": float(np.linalg.norm(centroid)),
        })

    # Save group summary files.
    class_summary_df = pd.DataFrame(class_summary_rows)
    class_summary_path = os.path.join(args.save_dir, "class_summary.csv")
    class_summary_df.to_csv(class_summary_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {class_summary_path}")

    ef_param_df = pd.DataFrame(ef_param_rows)
    ef_param_path = os.path.join(args.save_dir, "ef_param_stats.csv")
    ef_param_df.to_csv(ef_param_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {ef_param_path}")

    input_param_df_all = pd.concat(input_param_dfs, ignore_index=True) if input_param_dfs else pd.DataFrame()
    input_param_path = os.path.join(args.save_dir, "input_importance_parameter.csv")
    input_param_df_all.to_csv(input_param_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {input_param_path}")

    if data_summary_rows:
        data_summary_df = pd.DataFrame(data_summary_rows)
        data_summary_path = os.path.join(args.save_dir, "data_contribution_summary.csv")
        data_summary_df.to_csv(data_summary_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {data_summary_path}")
    else:
        data_summary_df = pd.DataFrame()

    if input_data_dfs:
        input_data_df_all = pd.concat(input_data_dfs, ignore_index=True)
        input_data_path = os.path.join(args.save_dir, "input_importance_data.csv")
        input_data_df_all.to_csv(input_data_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {input_data_path}")
    else:
        input_data_df_all = pd.DataFrame()

    if ef_data_dfs:
        ef_data_df_all = pd.concat(ef_data_dfs, ignore_index=True)
        ef_data_path = os.path.join(args.save_dir, "ef_data_contribution.csv")
        ef_data_df_all.to_csv(ef_data_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {ef_data_path}")
    else:
        ef_data_df_all = pd.DataFrame()

    # Top-k input importance tables.
    if len(input_param_df_all) > 0:
        input_param_top = (
            input_param_df_all.sort_values(["layer", "class_label", "importance_total"], ascending=[True, True, False])
            .groupby(["layer", "class_label"], as_index=False)
            .head(args.top_inputs)
        )
        top_param_path = os.path.join(args.save_dir, f"top{args.top_inputs}_input_importance_parameter.csv")
        input_param_top.to_csv(top_param_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {top_param_path}")

    if len(input_data_df_all) > 0:
        input_data_top = (
            input_data_df_all.sort_values(["layer", "class_label", "importance_total_data_weighted"], ascending=[True, True, False])
            .groupby(["layer", "class_label"], as_index=False)
            .head(args.top_inputs)
        )
        top_data_path = os.path.join(args.save_dir, f"top{args.top_inputs}_input_importance_data.csv")
        input_data_top.to_csv(top_data_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {top_data_path}")

    # Inter-class difference decomposition: explain what causes different
    # RSA classes within the same layer to differ in parameter space.
    print("\n===== Decomposing inter-class parameter differences within each layer =====")
    for layer_name, class_nodes_map in nodes_by_layer_class.items():
        if layer_name not in layer_params_map:
            continue
        params = layer_params_map[layer_name]
        labels = sorted(class_nodes_map.keys())
        if len(labels) < 2:
            continue
        for ia in range(len(labels)):
            for ib in range(ia + 1, len(labels)):
                class_a, class_b = labels[ia], labels[ib]
                nodes_a = class_nodes_map[class_a]
                nodes_b = class_nodes_map[class_b]
                block_rows, ef_rows_pair, input_rows_pair, dim_rows_pair, summary_pair = compute_inter_class_parameter_differences(
                    params=params,
                    nodes_a=nodes_a,
                    nodes_b=nodes_b,
                    layer_name=layer_name,
                    class_a=class_a,
                    class_b=class_b,
                    include_ef_weight=args.inter_class_include_ef_weight,
                    top_dims=args.top_inter_class_parameter_dims,
                )
                inter_class_block_rows.extend(block_rows)
                inter_class_ef_rows.extend(ef_rows_pair)
                inter_class_input_rows.extend(input_rows_pair)
                inter_class_top_dim_rows.extend(dim_rows_pair)
                inter_class_summary_rows.append(summary_pair)

    inter_summary_df = pd.DataFrame(inter_class_summary_rows)
    inter_summary_path = os.path.join(args.save_dir, "inter_class_difference_summary.csv")
    inter_summary_df.to_csv(inter_summary_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {inter_summary_path}")

    inter_block_df = pd.DataFrame(inter_class_block_rows)
    inter_block_path = os.path.join(args.save_dir, "inter_class_param_block_contribution.csv")
    inter_block_df.to_csv(inter_block_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {inter_block_path}")

    inter_ef_diff_df = pd.DataFrame(inter_class_ef_rows)
    inter_ef_diff_path = os.path.join(args.save_dir, "inter_class_ef_difference.csv")
    inter_ef_diff_df.to_csv(inter_ef_diff_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {inter_ef_diff_path}")

    inter_input_diff_df = pd.DataFrame(inter_class_input_rows)
    inter_input_diff_path = os.path.join(args.save_dir, "inter_class_input_difference.csv")
    inter_input_diff_df.to_csv(inter_input_diff_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {inter_input_diff_path}")

    if len(inter_input_diff_df) > 0:
        inter_input_top = (
            inter_input_diff_df
            .sort_values(["layer", "class_label_a", "class_label_b", "input_standardized_l2_sq"], ascending=[True, True, True, False])
            .groupby(["layer", "class_label_a", "class_label_b"], as_index=False)
            .head(args.top_inputs)
        )
        inter_input_top_path = os.path.join(args.save_dir, f"top{args.top_inputs}_inter_class_input_difference.csv")
        inter_input_top.to_csv(inter_input_top_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {inter_input_top_path}")

    inter_top_dim_df = pd.DataFrame(inter_class_top_dim_rows)
    inter_top_dim_path = os.path.join(args.save_dir, "inter_class_top_parameter_dimensions.csv")
    inter_top_dim_df.to_csv(inter_top_dim_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {inter_top_dim_path}")

    # If data-driven contribution analysis succeeded, also compare the classwise
    # actual output contribution and data-weighted input importance. These are
    # closer to functional differences than static parameter distances.
    data_pair_summary_df, data_pair_input_df, data_pair_ef_df = compute_pairwise_data_difference_tables(
        data_summary_df=data_summary_df,
        input_data_df_all=input_data_df_all,
        ef_data_df_all=ef_data_df_all,
        top_inputs=args.top_inputs,
    )
    if len(data_pair_summary_df) > 0:
        data_pair_summary_path = os.path.join(args.save_dir, "inter_class_data_contribution_difference.csv")
        data_pair_summary_df.to_csv(data_pair_summary_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {data_pair_summary_path}")
    if len(data_pair_input_df) > 0:
        data_pair_input_path = os.path.join(args.save_dir, f"top{args.top_inputs}_inter_class_data_input_difference.csv")
        data_pair_input_df.to_csv(data_pair_input_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {data_pair_input_path}")
    if len(data_pair_ef_df) > 0:
        data_pair_ef_path = os.path.join(args.save_dir, "inter_class_data_ef_difference.csv")
        data_pair_ef_df.to_csv(data_pair_ef_path, index=False, encoding="utf-8-sig")
        print(f"Saved: {data_pair_ef_path}")

    # Inter-class centroid distances.
    inter_rows = []
    for layer_name, centroid_map in centroids_by_layer.items():
        labels = sorted(centroid_map.keys())
        if len(labels) == 0:
            continue
        Cmat = np.stack([centroid_map[label] for label in labels], axis=0)
        dist_mat = squareform(pdist(Cmat, metric="euclidean")) if len(labels) > 1 else np.zeros((1, 1))

        for i, li in enumerate(labels):
            for j, lj in enumerate(labels):
                inter_rows.append({
                    "layer": layer_name,
                    "class_label_a": li,
                    "class_label_b": lj,
                    "centroid_l2_distance": float(dist_mat[i, j]),
                })

        heatmap_path = os.path.join(fig_dir, f"{sanitize_name(layer_name)}__inter_class_centroid_distance.png")
        plot_inter_class_heatmap(layer_name, labels, dist_mat, heatmap_path)

    inter_df = pd.DataFrame(inter_rows)
    inter_path = os.path.join(args.save_dir, "inter_class_distance.csv")
    inter_df.to_csv(inter_path, index=False, encoding="utf-8-sig")
    print(f"Saved: {inter_path}")

    # Figures for each group.
    print("\n===== Plotting figures =====")
    if len(input_param_df_all) > 0:
        for (layer_name, class_label), g in input_param_df_all.groupby(["layer", "class_label"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_label)}__top_input_importance_parameter.png",
            )
            plot_top_inputs(
                g,
                value_col="importance_total",
                title=f"{layer_name} / {class_label}: parameter input importance",
                save_path=p,
                top_k=args.top_inputs,
            )

    if len(input_data_df_all) > 0:
        for (layer_name, class_label), g in input_data_df_all.groupby(["layer", "class_label"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_label)}__top_input_importance_data.png",
            )
            plot_top_inputs(
                g,
                value_col="importance_total_data_weighted",
                title=f"{layer_name} / {class_label}: data-weighted input importance",
                save_path=p,
                top_k=args.top_inputs,
            )

    if len(ef_param_df) > 0:
        for (layer_name, class_label), g in ef_param_df.groupby(["layer", "class_label"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_label)}__ef_weighted_c_param.png",
            )
            plot_ef_bars(
                g,
                value_col="mean_abs_weighted_c",
                title=f"{layer_name} / {class_label}: elementary function parameter strength",
                save_path=p,
            )

    if len(ef_data_df_all) > 0:
        for (layer_name, class_label), g in ef_data_df_all.groupby(["layer", "class_label"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_label)}__ef_actual_output_contribution.png",
            )
            plot_ef_bars(
                g,
                value_col="mean_abs_actual_output",
                title=f"{layer_name} / {class_label}: actual elementary output contribution",
                save_path=p,
            )

    # Inter-class explanatory figures: these show which parameter blocks,
    # elementary functions, and input dimensions separate different RSA classes.
    if len(inter_block_df) > 0:
        for (layer_name, class_a, class_b), g in inter_block_df.groupby(["layer", "class_label_a", "class_label_b"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_a)}_vs_{sanitize_name(class_b)}__inter_class_block_difference.png",
            )
            plot_top_categories(
                g,
                label_col="block",
                value_col="standardized_contribution_ratio",
                title=f"{layer_name}: {class_a} vs {class_b} parameter-block difference",
                save_path=p,
                top_k=20,
            )

    if len(inter_input_diff_df) > 0:
        for (layer_name, class_a, class_b), g in inter_input_diff_df.groupby(["layer", "class_label_a", "class_label_b"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_a)}_vs_{sanitize_name(class_b)}__top_input_difference.png",
            )
            plot_top_inputs(
                g,
                value_col="input_standardized_l2_sq",
                title=f"{layer_name}: {class_a} vs {class_b} input-dimension difference",
                save_path=p,
                top_k=args.top_inputs,
            )

    if len(inter_ef_diff_df) > 0:
        for (layer_name, class_a, class_b), g in inter_ef_diff_df.groupby(["layer", "class_label_a", "class_label_b"]):
            p = os.path.join(
                fig_dir,
                f"{sanitize_name(layer_name)}__{sanitize_name(class_a)}_vs_{sanitize_name(class_b)}__ef_difference.png",
            )
            plot_ef_bars(
                g,
                value_col="ef_standardized_l2_sq",
                title=f"{layer_name}: {class_a} vs {class_b} elementary-function difference",
                save_path=p,
            )

    # Markdown summary for paper/report writing.
    report_path = os.path.join(args.save_dir, "analysis_report_template.md")
    write_report_template(report_path, args)
    print(f"Saved: {report_path}")

    print("\n===== Done =====")
    print(f"All outputs are under: {args.save_dir}")


# =============================================================================
# Report template
# =============================================================================


def write_report_template(path: str, args):
    text = f"""# Same-layer same-class neuron weight analysis

This report summarizes group-level analysis for neurons classified by Neuron-level RSA.

## Parameter vector

For neuron $i$ in layer $l$, the parameter vector is constructed as

$$
\\theta_{{l,i}} = [\\{{\\hat c_{{m,l,i,j}}\\}}_{{m,j}},
\\{{\\hat d_{{l,m,i}}\\}}_m, \\{{w^b_{{l,i,j}}\\}}_j],
$$

where, by default,

$$
\\hat c_{{m,l,i,j}} = s_{{mlp}} c_{{m,l,i,j}},
\\quad
\\hat d_{{l,m,i}} = s_{{mlp}} d_{{l,m,i}}.
$$

The elementary-function prefactor $w_{{l,m}}$ is intentionally omitted when
constructing the parameter vector. Use `--include_ef_weight_in_param_vector`
only if you want to restore the old behavior that multiplies by $w_{{l,m}}$.

The script computes the class centroid, intra-class variance, mean distance to centroid,
pairwise Euclidean distance, and pairwise cosine similarity.

## Parameter-based input importance

For class $\\mathcal C_k$ in layer $l$, the parameter-based input importance is

$$
I^{{param}}_{{l,k,j}} =
\\sum_m |s_{{mlp}} w_{{l,m}}| \\
\\frac{{1}}{{|\\mathcal C_k|}}\\sum_{{i\\in\\mathcal C_k}} |c_{{m,l,i,j}}|
+
\\frac{{1}}{{|\\mathcal C_k|}}\\sum_{{i\\in\\mathcal C_k}} |w^b_{{l,i,j}}|.
$$

Saved in `input_importance_parameter.csv`.

## Data-weighted input importance

If test data are available, the script also computes

$$
I^{{data}}_{{l,k,j}} =
\\sum_m |s_{{mlp}} w_{{l,m}}| \\
\\frac{{1}}{{|\\mathcal C_k|}}\\sum_{{i\\in\\mathcal C_k}} |c_{{m,l,i,j}}|
\\cdot \\mathbb E[|h_{{l-1,j}}|]
+
\\frac{{1}}{{|\\mathcal C_k|}}\\sum_{{i\\in\\mathcal C_k}} |w^b_{{l,i,j}}|
\\cdot \\mathbb E[|b(h_{{l-1,j}})|].
$$

Saved in `input_importance_data.csv`.

## Actual elementary-function contribution

For each elementary function $f_m$, the script estimates

$$
A_{{m,l,k}} = \\frac{{1}}{{|\\mathcal C_k|}}
\\sum_{{i\\in\\mathcal C_k}}
\\mathbb E_{{h_{{l-1}}}}
\\left[
\\left|
s_{{mlp}}w_{{l,m}}f_m\\left(\\sum_j c_{{m,l,i,j}}h_{{l-1,j}} + d_{{l,m,i}}\\right)
\\right|
\\right].
$$

Saved in `ef_data_contribution.csv`.

## Main CSV files

- `class_summary.csv`: class-level consistency and statistics.
- `ef_param_stats.csv`: elementary-function parameter statistics.
- `input_importance_parameter.csv`: parameter-space input importance.
- `input_importance_data.csv`: data-weighted input importance, if enabled.
- `data_contribution_summary.csv`: actual output contribution summary, if enabled.
- `inter_class_distance.csv`: centroid distances between different classes.
- `inter_class_difference_summary.csv`: same-layer class-pair summary explaining which branch/input/function dominates the difference.
- `inter_class_param_block_contribution.csv`: class-pair decomposition into elementary-function C, elementary-function D, and base_weight blocks.
- `inter_class_ef_difference.csv`: class-pair decomposition by elementary function.
- `inter_class_input_difference.csv`: class-pair decomposition by input dimension.
- `inter_class_top_parameter_dimensions.csv`: top individual parameter dimensions ranked by standardized class difference.
- `top*_inter_class_input_difference.csv`: top input dimensions for each same-layer class pair.
- `inter_class_data_contribution_difference.csv`: class-pair differences in actual output contribution, if data analysis is enabled.
- `top*_inter_class_data_input_difference.csv`: class-pair differences in data-weighted input importance, if data analysis is enabled.
- `inter_class_data_ef_difference.csv`: class-pair differences in actual elementary-function output contribution, if data analysis is enabled.
- `class_mean_params/*.npz`: class-wise mean and variance tensors.

## Inter-class difference interpretation

The new inter-class analysis compares every class pair within the same layer.
For two classes $a$ and $b$, it computes the class-mean parameter difference

$$
\\Delta_{a,b} = \\mu_{l,a} - \\mu_{l,b}.
$$

It then decomposes $\\Delta_{a,b}$ into elementary-function $C$ blocks,
elementary-function $D$ bias blocks, base weights, input dimensions, and
individual parameter dimensions. Raw differences indicate where the centroid
distance is large. Standardized differences indicate where the class difference
is large relative to within-class dispersion.

## Important runtime options

- `--scale_param_vector`: {args.scale_param_vector}
- `--include_ef_weight_in_param_vector`: {args.include_ef_weight_in_param_vector}
- `--standardize_vectors`: {args.standardize_vectors}
- `--r_threshold`: {args.r_threshold}
- `--min_group_size`: {args.min_group_size}
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


# =============================================================================
# CLI
# =============================================================================


def build_argparser():
    parser = argparse.ArgumentParser(
        description="Analyze same-layer same-class neurons after SymbolicKAN Neuron-level RSA classification."
    )

    # Paths.
    parser.add_argument(
        "--model_path",
        type=str,
        default="/home/aiofm/PycharmProjects/MyKANNet/15e-16_KAN_Symbolic_FinetuneParam/Last_SymbolicKAN_Para_Silu_1_fold_4L_-524-524-524_15_2.pt",
        help="Path to trained SymbolicKAN checkpoint."
    )
    parser.add_argument(
        "--class_csv",
        type=str,
        default="",
        help="Path to neuron-level RSA classification CSV. If empty, script tries --rsa_save_dir."
    )
    parser.add_argument(
        "--rsa_save_dir",
        type=str,
        default="/home/aiofm/PycharmProjects/MyKANNet/15e-16_KAN_Symbolic_RSA/neuron_level_rsa",
        help="Directory containing neuron_level_rsa_results*.csv from the RSA script."
    )
    parser.add_argument(
        "--save_dir",
        type=str,
        default="/home/aiofm/PycharmProjects/MyKANNet/15e-16_KAN_Symbolic_RSA/group_weight_analysis",
        help="Directory to save analysis outputs."
    )

    # Model settings. Defaults match the uploaded RSA script.
    parser.add_argument("--layers_hidden", type=str, default="33,524,524,524,70")
    parser.add_argument("--elementary_functions", type=str, default=",".join(DEFAULT_ELEMENTARY_FUNCTIONS))
    parser.add_argument("--base_activation", type=str, default="silu", choices=list(BASE_ACTIVATION_MAP.keys()))
    parser.add_argument("--scale_base", type=float, default=1.0)
    parser.add_argument("--scale_mlp", type=float, default=1.0)
    parser.add_argument("--checkpoint_key", type=str, default="parameter")

    # Classification filtering.
    parser.add_argument("--class_col", type=str, default="best_phys", help="Column used as class label.")
    parser.add_argument("--r_threshold", type=float, default=0.0, help="Keep neurons with best_r >= threshold if best_r exists.")
    parser.add_argument("--p_threshold", type=float, default=None, help="Optional best_p threshold.")
    parser.add_argument("--layers", type=str, default="", help="Optional comma-separated layer names, e.g., Layer1,Layer2.")
    parser.add_argument("--min_group_size", type=int, default=2, help="Minimum neurons in a layer/class group.")

    # Parameter vector settings.
    parser.add_argument(
        "--scale_param_vector",
        action="store_true",
        default=True,
        help=(
            "Use scale_mlp*C and scale_mlp*D in parameter vectors, but do NOT "
            "multiply by the elementary-function prefactor w_l,m. Default: True."
        )
    )
    parser.add_argument(
        "--unscaled_param_vector",
        action="store_false",
        dest="scale_param_vector",
        help="Use raw C and D in parameter vectors."
    )
    parser.add_argument(
        "--include_ef_weight_in_param_vector",
        action="store_true",
        default=False,
        help=(
            "Also multiply C and D by w_l,m when constructing parameter vectors. "
            "This restores the old behavior. Default: False."
        )
    )
    # Backward-compatible aliases. `--weighted_param_vector` now means scaled by
    # scale_mlp only; it does not include w_l,m unless
    # --include_ef_weight_in_param_vector is also set.
    parser.add_argument(
        "--weighted_param_vector",
        action="store_true",
        dest="scale_param_vector",
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--unweighted_param_vector",
        action="store_false",
        dest="scale_param_vector",
        help=argparse.SUPPRESS,
    )
    parser.add_argument("--exclude_bias_from_vector", action="store_true")
    parser.add_argument("--exclude_base_from_vector", action="store_true")
    parser.add_argument("--standardize_vectors", action="store_true", help="Z-score parameter vector dimensions within each layer before distance analysis.")

    # Dataset settings. These names are kept compatible with MyKANnetLoader_2.load_dataset(opt).
    parser.add_argument(
        "--data_root",
        type=str,
        default="/media/aiofm/F/20250723_k-fold-cross-validation-KAN/1-fold",
        help="Dataset root used by MyKANnetLoader_2.load_dataset."
    )
    parser.add_argument("--batchSize", type=int, default=5120)
    parser.add_argument("--max_contribution_samples", type=int, default=2000)
    parser.add_argument("--forward_batch", type=int, default=512)
    parser.add_argument("--no_dataset_contribution", action="store_true", help="Only perform parameter-space analysis.")
    parser.add_argument("--strict_dataset_contribution", action="store_true", help="Raise error if dataset contribution analysis fails.")

    # Inter-class difference decomposition.
    parser.add_argument(
        "--inter_class_include_ef_weight",
        action="store_true",
        default=True,
        help=(
            "When decomposing same-layer inter-class differences, multiply C and D "
            "by scale_mlp * ef_weight so branch differences reflect their effective "
            "contribution in the layer. ef_weight itself is shared within a layer; "
            "this option only rescales branch contribution sizes. Default: True."
        ),
    )
    parser.add_argument(
        "--inter_class_exclude_ef_weight",
        action="store_false",
        dest="inter_class_include_ef_weight",
        help="For inter-class decomposition, use scale_mlp*C and scale_mlp*D without ef_weight.",
    )
    parser.add_argument(
        "--top_inter_class_parameter_dims",
        type=int,
        default=30,
        help="Number of top parameter dimensions saved per same-layer class pair.",
    )

    # Misc.
    parser.add_argument("--top_inputs", type=int, default=30)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--cpu", action="store_true")

    return parser


def main():
    parser = build_argparser()
    args = parser.parse_args()
    analyze(args)


if __name__ == "__main__":
    main()
